MES.WEB/Controllers/DefectController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using MES.BLL.DTO;
using MES.BLL.Infrastructure;
using MES.BLL.Interfaces;
using MES.DAL.Entities;
using MES.DAL.Interfaces;
using MES.WEB.Models;

namespace MES.WEB.Controllers
{
    public class DefectController : Controller
    {
        private readonly IDefectService _service;
        private readonly IUnitOfWork _db;

        public DefectController(IDefectService service, IUnitOfWork db)
        {
            _service = service;
            _db = db;
        }

        /// <summary>
        /// Добавить детали в брак
        /// </summary>
        /// <returns>PartialView</returns>
        public ActionResult AddDefectJmtDetailPartial()
        {
            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;
            DefectDetailVm defect = new DefectDetailVm { Date = DateTime.Now };
            return PartialView(defect);
        }

        [HttpPost]
        public async Task<ActionResult> AddDefectJmtDetailPartial(DefectDetailVm defect)
        {
            defect.UserId = User.Identity.GetUserId<int>();
            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;

            if (!ModelState.IsValid) return PartialView(defect);

            var result = await _service.AddDefectDetailAsync(Mapper.Map<DefectDetailDto>(defect));

            if (result.Succedeed)
            {
                string prodName = (await _db.Details.GetAsync(defect.DetailId)).Name;
                ChatUser user = Mapper.Map<ChatUser>(await _db.Users.GetAsync(defect.UserId));
                ChatMessage message = new ChatMessage
                {
                    Date = DateTime.Now,
                    Text = $"Я добавил в брак {prodName} {defect.Count}шт.",
                    User = user
                };
                if (ChatController.listMessage == null) ChatController.listMessage = new List<ChatMessage>();
                ChatController.listMessage.Add(message);
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        //История брака на склад
        public async Task<ActionResult> HistDefectPartial(string startDate, string endDate)
        {
            var defect = Mapper.Map<IEnumerable<DefectDetailDisplayDto>, List<DefectDetailDisplayVm>>(await _service.ShowDefectDetailAsync(startDate, endDate));
            return PartialView(defect);
        }

        public async Task<ActionResult> QuantityDefectPartial(string startDate, string endDate)
        {
            var defect = Mapper.Map<IEnumerable<DefectQuantityDto>, List<DefectQuantityVm>>(await _service.ShowDefectCountAsync(startDate, endDate));
            return PartialView("_QuantityDefectPartial", defect);
        }

        public ActionResult Defect()
        {
            var now = DateTime.Now;
            var date = new DateVm
            {
                StartDate = new DateTime(now.Year, now.Month, 1),
                EndDate = now
            };
            return View(date);
        }


        //Удаление Данных о браковке деталей
        public async Task<ActionResult> DeleteDefect(int id)
        {
            var result = await _service.DeleteDefectDetailAsync(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //Редактирование Данных о браковке деталей
        public async Task<ActionResult> EditDefectPartial(int id)
        {
            var defect = Mapper.Map<DefectDetailVm>(await _service.GetDefect(id));

            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;

            return PartialView(defect);
        }

        [HttpPost]
        public async Task<ActionResult> EditDefectPartial(DefectDetailVm defect)
        {
            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;

            if (!ModelState.IsValid) return View(defect);

            var result = await _service.EditDefectDetailAsync(Mapper.Map<DefectDetail>(defect));

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

MES.WEB/Views/Defect/AddDefectJmtDetailPartial.cshtml
@model MES.WEB.Models.DefectDetailVm


<div id="modalContent" class="modal-content modal-danger">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Добавить в брак</h4>
    </div>

    @using (Ajax.BeginForm("AddDefectJmtDetailPartial",  new AjaxOptions
    {
        UpdateTargetId = "modalContent",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "unloadModal"
    }))
    {
        <div class="modal-body">

            @Html.AntiForgeryToken()

            <div class="form-horizontal">

            
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DetailId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DetailId, ViewBag.Detail as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DetailId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Отмена</button>
            <button type="submit" value="Create" class="btn btn-outline">Добавить</button>
        </div>
    }
</div>



@section scripts {


    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datepicker")



    <script>
        $(function () {
            $(document.body).on('click',
                '[data-val-required]',
                function (ev) {
                    $(ev.target).attr('required', 'true');
                });

            //Date picker
            $('#Date').datepicker({
                language: "ru",
                orientation: "bottom auto",
                todayHighlight: true,
                todayBtn: "linked"

            });
        })
    </script>


   



}

MES.WEB/Views/Defect/Defect.cshtml
@model MES.WEB.Models.DateVm


@{
    ViewBag.Title = "Брак деталей";
}

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div id="alert-message"></div>
<p>
    <a href="@Url.Action("AddDefectJmtDetailPartial")" id="addId" class="btn btn-danger addtn">Добавить в брак</a>
</p>



<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">История прихода деталей на склад</h3>
    </div>
    <!-- /.box-header -->
    <br />
    <div class="form-inline">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <hr />
    <div class="box-body">
        <div id="results2">
        </div>
    </div>
    <hr />
    <div class="box-body">
        <div id="results">
        </div>
    </div>

</div>




@section scripts
{

<script>
        function view() {
            var startDate = $('#StartDate').val();
            startDate = encodeURIComponent(startDate);
            var endDate = $('#EndDate').val();
            endDate = encodeURIComponent(endDate);
            $('#results').load('@Url.Action("HistDefectPartial", "Defect")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);
             $('#results2').load('@Url.Action("QuantityDefectPartial", "Defect")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);
        }


        $(function () {
            var idToUpdate = $('#results');
            $.get("/Defect/HistDefectPartial",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });

        $(function () {
            var idToUpdate = $('#results2');
            $.get("/Defect/QuantityDefectPartial",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });

        document.getElementById("stock").className = "active treeview menu-open";
        document.getElementById("defectJmtDetail").className = "active";
</script>


}

MES.WEB/Views/Defect/EditDefectPartial.cshtml
@model MES.WEB.Models.DefectDetailVm

<div id="modalContent" class="modal-content modal-warning">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Редактировать</h4>
    </div>

    @using (Ajax.BeginForm("EditDefectPartial",  new AjaxOptions
    {
        UpdateTargetId = "modalContent",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "unloadModal"
    }))
    {
        <div class="modal-body">

            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DetailId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DetailId, ViewBag.Detail as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DetailId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Отмена</button>
            <button type="submit" value="Create" class="btn btn-outline">Изменить</button>
        </div>
    }
</div>



@section scripts {


    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datepicker")



    <script>
        $(function () {
            $(document.body).on('click',
                '[data-val-required]',
                function (ev) {
                    $(ev.target).attr('required', 'true');
                });

            //Date picker
            $('#Date').datepicker({
                language: "ru",
                orientation: "bottom auto",
                todayHighlight: true,
                todayBtn: "linked"

            });
        })
    </script>






}

MES.WEB/Views/Defect/HistDefectPartial.cshtml
@model IEnumerable<MES.WEB.Models.DefectDetailDisplayVm>
<h4>История брака</h4>
<table id="example" class="table table-striped dataTable">

    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NameDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        @if (User.IsInRole("admin"))
        {
            <th></th>
        }
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NameDetail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            @if (User.IsInRole("admin"))
            {
                <td>
                    @Html.ActionLink("Редактировать", "EditDefectPartial", new { id = item.Id }, new { @class = "text-orange" }) |
                    <a class="text-danger" onclick="deleteElement(event, this)" href="@Url.Action("DeleteDefect", new { id = item.Id })">Удалить</a>
                </td>
            }

        </tr>
    }

</table>



<script>
    $(function () {
        $.ajaxSetup({ cache: false });
        $(".text-orange").click(function (e) {

            e.preventDefault();
            $.get(this.href,
                function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
        });
    })
</script>


<script type="text/javascript" charset="utf-8">
    $("#example").dataTable(
        {

            language: {
                "processing": "Подождите...",
                "search": "Поиск:",
                "lengthMenu": "Показать _MENU_ записей",
                "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
                "infoEmpty": "Записи с 0 до 0 из 0 записей",
                "infoFiltered": "(отфильтровано из _MAX_ записей)",
                "infoPostFix": "",
                "loadingRecords": "Загрузка записей...",
                "zeroRecords": "Записи отсутствуют.",
                "emptyTable": "В таблице отсутствуют данные",
                "paginate": {
                    "first": "Первая",
                    "previous": "Предыдущая",
                    "next": "Следующая",
                    "last": "Последняя"
                },
                "aria": {
                    "sortAscending": ": активировать для сортировки столбца по возрастанию",
                    "sortDescending": ": активировать для сортировки столбца по убыванию"
                }
            },

            "aoColumns": [

                { "sType": "ruDate" },
                null,
                null,
                null,
                null
            ],
            "aaSorting": [[0, 'desc']]
        });

    jQuery.extend(jQuery.fn.dataTableExt.oSort,
        {
            "ruDate-asc": function (a, b) {
                var ruDatea = $.trim(a).split('.');
                var ruDateb = $.trim(b).split('.');

                if (ruDatea[2] * 1 < ruDateb[2] * 1)
                    return 1;
                if (ruDatea[2] * 1 > ruDateb[2] * 1)
                    return -1;
                if (ruDatea[2] * 1 == ruDateb[2] * 1) {
                    if (ruDatea[1] * 1 < ruDateb[1] * 1)
                        return 1;
                    if (ruDatea[1] * 1 > ruDateb[1] * 1)
                        return -1;
                    if (ruDatea[1] * 1 == ruDateb[1] * 1) {
                        if (ruDatea[0] * 1 < ruDateb[0] * 1)
                            return 1;
                        if (ruDatea[0] * 1 > ruDateb[0] * 1)
                            return -1;
                    } else
                        return 0;
                }
            },

            "ruDate-desc": function (a, b) {
                var ruDatea = $.trim(a).split('.');
                var ruDateb = $.trim(b).split('.');

                if (ruDatea[2] * 1 < ruDateb[2] * 1)
                    return -1;
                if (ruDatea[2] * 1 > ruDateb[2] * 1)
                    return 1;
                if (ruDatea[2] * 1 == ruDateb[2] * 1) {
                    if (ruDatea[1] * 1 < ruDateb[1] * 1)
                        return -1;
                    if (ruDatea[1] * 1 > ruDateb[1] * 1)
                        return 1;
                    if (ruDatea[1] * 1 == ruDateb[1] * 1) {
                        if (ruDatea[0] * 1 < ruDateb[0] * 1)
                            return -1;
                        if (ruDatea[0] * 1 > ruDateb[0] * 1)
                            return 1;
                    } else
                        return 0;
                }
            }
        });


</script>

MES.WEB/Views/Defect/_QuantityDefectPartial.cshtml
@model IEnumerable<MES.WEB.Models.DefectQuantityVm>

<h4>Брак за период</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NameDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Count)
        </th>       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NameDetail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Count)
        </td>       
    </tr>
}

</table>