MES.WEB/Controllers/AnalyticsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using MES.BLL.DTO;
using MES.BLL.Interfaces;
using MES.WEB.Models;

namespace MES.WEB.Controllers
{
    [Authorize]
    public class AnalyticsController : Controller
    {
        private readonly IAnalyticsService _service;
        

        public AnalyticsController(IAnalyticsService service)
        {
            _service = service;            
        }

        public ActionResult Index()
        {
            var now = DateTime.Now;
            var date = new DateVm
            {
                StartDate = new DateTime(now.Year, now.Month, 1),
                EndDate = now
            };

            return View(date);
        }

        public async Task<ActionResult> RemainingDetails()
        {
            var d52001 = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(await _service.GetDetailOnProduct("5200-01"));
            //Random random = new Random();
            //for (int i = 0; i < 100; i++)
            //{
            //    DateTime date1 = new DateTime(2017, random.Next(1, 12), random.Next(1, 30));
            //    _db.Shipments.Create(new Shipment
            //    {
            //        Date = date1,
            //        BoxingVariant = BoxingVariant.Годная,
            //        ProductId = 3,
            //        UserId = 1,
            //        Quantity = random.Next(300, 3000)

            //    });
            //}
            //await _db.Commit();
            return PartialView("_RemainingDetails", d52001);
        }

        public async Task<ActionResult> RemainingDetailsIndex()
        {
            var d52001 = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(await _service.GetDetailOnProduct("5200-01"));
            return PartialView("_RemainingDetailsIndex", d52001);
        }

        public async Task<ActionResult> HowManySoldered(string startDate, string endDate)
        {
            var solderings = Mapper.Map<IEnumerable<SolderingCountDto>, List<SolderingCountVm>>(
                await _service.ShowSolderingsCountAsync(startDate, endDate));

            return PartialView("_HowManySoldered", solderings);
        }

        public async Task<ActionResult> HowManySolderedModal(string startDate, string endDate)
        {
            var solderings = Mapper.Map<IEnumerable<SolderingCountDto>, List<SolderingCountVm>>(
                await _service.ShowSolderingsCountAsync(startDate, endDate));

            return PartialView("_HowManySolderedModal", solderings);
        }

        public async Task<ActionResult> CheckInfo(string startDate, string endDate)
        {
            var check = Mapper.Map<ChekDetailsVm>(
                await _service.ShowCheckInfo(startDate, endDate));

            return PartialView("_CheckInfo", check);
        }

        public async Task<ActionResult> CheckInfoModal(string startDate, string endDate)
        {
            var check = Mapper.Map<ChekDetailsVm>(
                await _service.ShowCheckInfo(startDate, endDate));
            return PartialView("_CheckInfoModal", check);
        }

        public  async Task<ActionResult> ShipmentChart(string startDate, string endDate)
        {
            var check = Mapper.Map<IEnumerable<ShipmentChartDto>, List<ShipmentChartVm>>(
                 await _service.ShowShipmentAsync(startDate, endDate));

            return PartialView("_ShipmentChart", check);
        }

        public async Task<ActionResult> ShipmentChartModal(string startDate, string endDate)
        {
            var check = Mapper.Map<IEnumerable<ShipmentChartDto>, List<ShipmentChartVm>>(
                await _service.ShowShipmentAsync(startDate, endDate));

            return PartialView("_ShipmentChartModal", check);
        }

        public async Task<ActionResult> QualityIndicatorsChart(string startDate, string endDate)
        {
            var result = Mapper.Map<IEnumerable<QualityIndicators>, List<QualityIndicatorsVm>>(
                await _service.QualityIndicators520001(startDate, endDate));

            return PartialView("_QualityIndicatorsChart", result);
        }
    }
}

MES.WEB/Views/Analytics/Index.cshtml
@model MES.WEB.Models.DateVm
@{
    ViewBag.Title = "Графики";
}


<div id="modDialog" class="modal fade ">
    <div id="dialogContent" class="modal-dialog col-md-10"></div>
</div>

<div class="box-body">
    @Html.AntiForgeryToken()

    <div class="form-inline">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
</div>

<section class="content">
    <div class="row">
        <div class="col-md-6">
            <!-- AREA CHART -->
            <!-- LINE CHART -->

            <a href="@Url.Action("ShipmentChartModal")" class="charts">
                <div id="results4">
                </div>
            </a>

            <a href="@Url.Action("HowManySolderedModal")" class="charts">
                <div id="results2">
                </div>
            </a>
            <!-- /.box -->
            <!-- BAR CHART -->
            <!-- /.box -->
            <!-- /.box -->

        </div>
        <!-- /.col (LEFT) -->
        <div class="col-md-6">

            <!-- /.box -->
            <!-- DONUT CHART -->

            <a href="@Url.Action("RemainingDetails")" class="charts">
                <div id="results">
                </div>
            </a>

            <a href="@Url.Action("CheckInfoModal")" class="charts">
                <div id="results3">
                </div>
            </a>
        </div>

        <div class="col-md-6">
            <div id="results5">
            </div>
        </div>

        <!-- /.col (RIGHT) -->
    </div>
    <!-- /.row -->

</section>


@section scripts
{

    <script>



        $(function () {
            var idToUpdate = $('#results');
            $.get("/Analytics/RemainingDetailsIndex",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });

        $(function () {
            var idToUpdate = $('#results2');
            $.get("/Analytics/HowManySoldered",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });

        $(function () {
            var idToUpdate = $('#results3');
            $.get("/Analytics/CheckInfo",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });

        $(function () {
            var idToUpdate = $('#results4');
            $.get("/Analytics/ShipmentChart",
                function (data) {
                    $(idToUpdate).html(data);
                });
    });

    $(function () {
        var idToUpdate = $('#results5');
        $.get("/Analytics/QualityIndicatorsChart",
            function (data) {
                $(idToUpdate).html(data);
            });
    });

        function view() {
            var startDate = $('#StartDate').val();
            startDate = encodeURIComponent(startDate);
            var endDate = $('#EndDate').val();
            endDate = encodeURIComponent(endDate);
            $('#results').load('@Url.Action("RemainingDetailsIndex", "Analytics")');
            $('#results2').load('@Url.Action("HowManySoldered", "Analytics")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);
            $('#results3').load('@Url.Action("CheckInfo", "Analytics")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);
            $('#results4').load('@Url.Action("ShipmentChart", "Analytics")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);
            $('#results5').load('@Url.Action("QualityIndicatorsChart", "Analytics")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);
        }

        document.getElementById('analytics').className = "active";
    </script>

}

MES.WEB/Views/Analytics/_CheckInfo.cshtml
@model MES.WEB.Models.ChekDetailsVm

<div class="box external-event">
    <div class="box-header with-border">
        <h3 class="box-title">Результаты проверки 5200-01</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <div class="box-body">
        <div class="chart">
            <div id="container" width="800" height="450">
                <canvas id="chekChart"></canvas>
            </div>

        </div>
    </div>
</div>





<script>
    new Chart(document.getElementById("chekChart"), {
        type: 'pie',
        data: {
            labels: ["Целые", "Крышка М", "Крышка №", "Трубка", "Корпус", "Брак", "Прочее", "Центр"],
            datasets: [{
                label: "Population (millions)",
                backgroundColor: ["#00a65a", "#f39c12", "#00c0ef'", "#3c8dbc", "#d2d6de", "#f56954","#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                data: [@Html.Raw(Json.Encode(Model.Airtight)),@Html.Raw(Json.Encode(Model.CapM)),
                    @Html.Raw(Json.Encode(Model.CapN)),@Html.Raw(Json.Encode(Model.Tube)),
                    @Html.Raw(Json.Encode(Model.Housing)),
                    @Html.Raw(Json.Encode(Model.Defect)),@Html.Raw(Json.Encode(Model.Other)),
                    @Html.Raw(Json.Encode(Model.Center))]
            }]
        }
    });
</script>

MES.WEB/Views/Analytics/_CheckInfoModal.cshtml
@model MES.WEB.Models.ChekDetailsVm
<div id="modalContent" class="modal-content" style="width: 98vw; height: 100%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Результаты проверки 5200-01</h4>
    </div>
    <div class="modal-body">
        <div class="chart">
            <canvas id="chekChart2" style="height: 229px; width: 594px;" width="742" height="286"></canvas>
        </div>
    </div>
</div>


<script>
    new Chart(document.getElementById("chekChart2"), {
        type: 'pie',
        data: {
            labels: ["Целые", "Крышка М", "Крышка №", "Трубка", "Корпус", "Брак", "Прочее", "Центр"],
            datasets: [{
                label: "Population (millions)",
                backgroundColor: ["#00a65a", "#f39c12", "#00c0ef'", "#3c8dbc", "#d2d6de", "#f56954","#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                data: [@Html.Raw(Json.Encode(Model.Airtight)),@Html.Raw(Json.Encode(Model.CapM)),
                    @Html.Raw(Json.Encode(Model.CapN)),@Html.Raw(Json.Encode(Model.Tube)),
                    @Html.Raw(Json.Encode(Model.Housing)),
                    @Html.Raw(Json.Encode(Model.Defect)),@Html.Raw(Json.Encode(Model.Other)),
                    @Html.Raw(Json.Encode(Model.Center))]
            }]
        }
    });
</script>

MES.WEB/Views/Analytics/_HowManySoldered.cshtml
@model IEnumerable<MES.WEB.Models.SolderingCountVm>
<div class="box external-event">
    <div class="box-header with-border">
        <h3 class="box-title">Сколько спаяно</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <div class="box-body">
        <div class="chart">
            <div id="container" width="800" height="450">
                <canvas id="solderingsChart"></canvas>
            </div>

        </div>
    </div>
</div>





<script>
    new Chart(document.getElementById("solderingsChart"), {
        type: 'pie',
        data: {
            labels: @Html.Raw(Json.Encode(Model.Select(x=>x.ProductName))),
            datasets: [{
                label: "Population (millions)",
                backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
                data:  @Html.Raw(Json.Encode(Model.Select(x => x.Quantity)))
            }]
        }
    });
</script>
  

MES.WEB/Views/Analytics/_HowManySolderedModal.cshtml
@model IEnumerable<MES.WEB.Models.SolderingCountVm>
<div id="modalContent" class="modal-content" style="width: 98vw; height: 100%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Сколько спаяно</h4>
    </div>
    <div class="modal-body">
        <div class="chart">
            <canvas id="solderingsChart2"  style="height: 229px; width: 594px;" width="742" height="286"></canvas>
        </div>
    </div>
</div>





<script>
    new Chart(document.getElementById("solderingsChart2"), {
        type: 'doughnut',
        data: {
            labels: @Html.Raw(Json.Encode(Model.Select(x=>x.ProductName))),
            datasets: [{
                label: "Population (millions)",
                backgroundColor: ["#f56954", "#00a65a", "#f39c12", "#00c0ef'", "#3c8dbc", "#d2d6de"],
                data:  @Html.Raw(Json.Encode(Model.Select(x => x.Quantity)))
            }]
        }
    });
</script>

MES.WEB/Views/Analytics/_QualityIndicatorsChart.cshtml
@model IEnumerable<MES.WEB.Models.QualityIndicatorsVm>

<div class="box external-event">
    <div class="box-header with-border">
        <h3 class="box-title">Показатель качества</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <div class="box-body">
        <div class="chart">
            <div id="container" width="742" height="286">
                <canvas id="quality"></canvas>
            </div>

        </div>
    </div>
</div>





<script>
    var ctx = document.getElementById("quality").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: @Html.Raw(Json.Encode(Model.Select(x=>x.ProducName))),
            datasets: [{
                 label: 'Брак',
                    data: @Html.Raw(Json.Encode(Model.Select(x=>x.QuantityDefect))),
                    backgroundColor:
                        'rgba(255, 50, 64, 1)'
                    ,
                    borderColor:
                        'rgba(255, 159, 64, 1)'
                    ,
                    borderWidth: 1
            },
                {
                     label: 'Всего',
        data: @Html.Raw(Json.Encode(Model.Select(x => x.Quantity))),
    backgroundColor:
    'rgba(50, 180, 0, 1)'
        ,
        borderColor:
    'rgba(255, 159, 64, 1)'
        ,
        borderWidth: 1

                }
                ]
        },
        options: {
            tooltips: {
                mode: 'index',
                intersect: false
            },
            responsive: true,
            scales: {
                xAxes: [{
                    stacked: true,
                }],
                yAxes: [{
                    stacked: true
                }]
            }
        }
    });
</script>

MES.WEB/Views/Analytics/_RemainingDetails.cshtml
@model IEnumerable<MES.WEB.Models.DetailVm>


<div id="modalContent" class="modal-content" style="width: 98vw; height: 100%">
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
    <h4 class="modal-title">Сколько теплообменников 5200-01 можно собрать</h4>
</div>
    <div class="modal-body">
        <div class="chart">
            <canvas id="Chart5200012"  style="height: 229px; width: 594px;" width="742" height="286"></canvas>
        </div>
    </div>
</div>




 <script>
     var ctx = document.getElementById("Chart5200012").getContext('2d');
     var myChart = new Chart(ctx, {
         type: 'bar',
         data: {
             labels: @Html.Raw(Json.Encode(Model.Select(x=>x.Name))),
             datasets: [{
                 label: '5200-01',
                 data: @Html.Raw(Json.Encode(Model.Select(x=>x.Quantityq))),
                 backgroundColor:
                     'rgba(255, 159, 64, 1)'
                 ,
                 borderColor:
                     'rgba(255, 159, 64, 1)'
                 ,
                 borderWidth: 1
             }]
         },
         options: {
             scales: {
                 yAxes: [{
                     ticks: {
                         beginAtZero: true
                           
                     }
                 }]
             }
                
         }
     });

     
 </script>

MES.WEB/Views/Analytics/_RemainingDetailsIndex.cshtml
@model IEnumerable<MES.WEB.Models.DetailVm>


<div class="box external-event">
    <div class="box-header with-border">
        <h3 class="box-title">Сколько теплообменников 5200-01 можно собрать</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <div class="box-body">
        <div class="chart">
            <div id="container" width="742" height="286">
                <canvas id="Chart520001"></canvas>
            </div>

        </div>
    </div>
</div>





    <script>
        var ctx = document.getElementById("Chart520001").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: @Html.Raw(Json.Encode(Model.Select(x=>x.Name.Substring(0,2)))),
                datasets: [{
                    label: '5200-01',
                    data: @Html.Raw(Json.Encode(Model.Select(x=>x.Quantityq))),
                    backgroundColor:
                        'rgba(255, 159, 64, 1)'
                    ,
                    borderColor:
                        'rgba(255, 159, 64, 1)'
                    ,
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                           
                        }
                    }]
                }
                
            }
        });
    </script>
  

MES.WEB/Views/Analytics/_ShipmentChart.cshtml
@using System.Globalization
@model IEnumerable<MES.WEB.Models.ShipmentChartVm>


<div class="box external-event">
    <div class="box-header with-border">
        <h3 class="box-title">Отгрузки</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <div class="box-body">
        <div class="chart">
            <div id="container" width="742" height="286">
                <canvas id="shipmentChart"></canvas>
            </div>

        </div>
    </div>
</div>





<script>
    var ctx = document.getElementById("shipmentChart").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "6500").Select(x=> x.Date.ToString("MMMM", new CultureInfo("ru-RU"))))),
            datasets: [{
                            label: '5200-01',
                data: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "5200-01").Select(x=>x.Quantity))),

                            backgroundColor: "red",
                            borderColor: "red",
                fill: false

            },
            {
                            label: '6500',
                data: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "6500").Select(x=>x.Quantity))),
                borderColor: "green",
                backgroundColor: "green",
                fill: false

                },
            {
                            label: '5200',
                data: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "5200").Select(x=>x.Quantity))),
                borderColor: "blue",
                backgroundColor: "blue",
                fill: false

            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true


                    }
            }]
            }

        }
    });
</script>
  

MES.WEB/Views/Analytics/_ShipmentChartModal.cshtml
@model IEnumerable<MES.WEB.Models.ShipmentChartVm>
@using System.Globalization

<div id="modalContent" class="modal-content" style="width: 98vw; height: 100%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Сколько спаяно</h4>
    </div>
    <div class="modal-body">
        <div class="chart">
            <canvas id="shipmentChart2" style="height: 229px; width: 594px;" width="742" height="286"></canvas>
        </div>
    </div>
</div>





<script>
    var ctx = document.getElementById("shipmentChart2").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "6500").Select(x=> x.Date.ToString("MMMM", new CultureInfo("ru-RU"))))),
            datasets: [{
                    label: '5200-01',
                    data: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "5200-01").Select(x=>x.Quantity))),

                    backgroundColor: "red",
                    borderColor: "red",
                    fill: false

                },
                {
                    label: '6500',
                    data: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "6500").Select(x=>x.Quantity))),
                    borderColor: "green",
                    backgroundColor: "green",
                    fill: false

                },
                {
                    label: '5200',
                    data: @Html.Raw(Json.Encode(Model.Where(w=>w.ProducName== "5200").Select(x=>x.Quantity))),
                    borderColor: "blue",
                    backgroundColor: "blue",
                    fill: false

                }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true


                    }
                }]
            }

        }
    });
</script>