MES.WEB/Controllers/DefectController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using MES.BLL.DTO;
using MES.BLL.Infrastructure;
using MES.BLL.Interfaces;
using MES.DAL.Entities;
using MES.DAL.Interfaces;
using MES.WEB.Models;

namespace MES.WEB.Controllers
{
    public class DefectController : Controller
    {
        private readonly IDefectService _service;
        private readonly IUnitOfWork _db;

        public DefectController(IDefectService service, IUnitOfWork db)
        {
            _service = service;
            _db = db;
        }

        /// <summary>
        /// Добавить детали в брак
        /// </summary>
        /// <returns>PartialView</returns>
        public ActionResult AddDefectJmtDetailPartial()
        {
            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;
            DefectDetailVm defect = new DefectDetailVm { Date = DateTime.Now };
            return PartialView(defect);
        }

        [HttpPost]
        public async Task<ActionResult> AddDefectJmtDetailPartial(DefectDetailVm defect)
        {
            defect.UserId = User.Identity.GetUserId<int>();
            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;

            if (!ModelState.IsValid) return PartialView(defect);

            var result = await _service.AddDefectDetailAsync(Mapper.Map<DefectDetailDto>(defect));

            if (result.Succedeed)
            {
                string prodName = (await _db.Details.GetAsync(defect.DetailId)).Name;
                ChatUser user = Mapper.Map<ChatUser>(await _db.Users.GetAsync(defect.UserId));
                ChatMessage message = new ChatMessage
                {
                    Date = DateTime.Now,
                    Text = $"Я добавил в брак {prodName} {defect.Count}шт.",
                    User = user
                };
                if (ChatController.listMessage == null) ChatController.listMessage = new List<ChatMessage>();
                ChatController.listMessage.Add(message);
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }


        //История брака на склад
        public async Task<ActionResult> HistDefectPartial(string startDate, string endDate)
        {
            var defect = Mapper.Map<IEnumerable<DefectDetailDisplayDto>, List<DefectDetailDisplayVm>>(await _service.ShowDefectDetailAsync(startDate, endDate));
            return PartialView(defect);
        }

        public async Task<ActionResult> QuantityDefectPartial(string startDate, string endDate)
        {
            var defect = Mapper.Map<IEnumerable<DefectQuantityDto>, List<DefectQuantityVm>>(await _service.ShowDefectCountAsync(startDate, endDate));
            return PartialView("_QuantityDefectPartial", defect);
        }

        public ActionResult Defect()
        {
            var now = DateTime.Now;
            var date = new DateVm
            {
                StartDate = new DateTime(now.Year, now.Month, 1),
                EndDate = now
            };
            return View(date);
        }


        //Удаление Данных о браковке деталей
        public async Task<ActionResult> DeleteDefect(int id)
        {
            var result = await _service.DeleteDefectDetailAsync(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //Редактирование Данных о браковке деталей
        public async Task<ActionResult> EditDefectPartial(int id)
        {
            var defect = Mapper.Map<DefectDetailVm>(await _service.GetDefect(id));

            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;

            return PartialView(defect);
        }

        [HttpPost]
        public async Task<ActionResult> EditDefectPartial(DefectDetailVm defect)
        {
            var details = Mapper.Map<IEnumerable<DetailDTO>, List<DetailVm>>(_service.GetDetailsJmt());
            SelectList detailList = new SelectList(details, "Id", "Name");
            ViewBag.Detail = detailList;

            if (!ModelState.IsValid) return View(defect);

            var result = await _service.EditDefectDetailAsync(Mapper.Map<DefectDetail>(defect));

            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

MES.WEB/Controllers/StockController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using MES.BLL.DTO;
using MES.BLL.Interfaces;
using MES.DAL.Entities;
using MES.DAL.Interfaces;
using MES.WEB.Models;

namespace MES.WEB.Controllers
{
    [Authorize]
    public class StockController : Controller
    {
        private readonly IStockService _stockOn;
        private readonly IUnitOfWork _db;

        public StockController(IStockService stockOn, IUnitOfWork db)
        {
            _stockOn = stockOn;
            _db = db;
        }

        public ActionResult Index()
        {
            return View();
        }

        // Остаток деталей на складе
        public async Task<ActionResult> StockBalanceJmt()
        {
            var detail = Mapper.Map<IEnumerable<Detail>, List<DetailVm>>(await _db.Details.GetAllAsync());
            
            return PartialView("_StockBalanceJmt",detail);
        }

        
       

        public ActionResult AddDetail()
        {
            return PartialView("_AddDetail");
        }

        [HttpPost]
        public async Task<ActionResult> AddDetail(DetailVm modal)
        {
            if (!ModelState.IsValid) return PartialView("_AddDetail",modal);
            var result = await _stockOn.CreateDetail(Mapper.Map<DetailDTO>(modal));
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> EditJmtDetail(int id)
        {
            var detail = Mapper.Map<DetailVm>(await _stockOn.GetDetail(id));
            return PartialView("_EditJmtDetail", detail);
        }

        [HttpPost]
        public async Task<ActionResult> EditJmtDetail(DetailVm detail)
        {
            if (!ModelState.IsValid) return PartialView("_EditJmtDetail", detail);
            var result = await _stockOn.EditDetail(Mapper.Map<DetailDTO>(detail));
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Delete(int id)
        {
            var result = await _stockOn.DeleteDetailAsync(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

MES.WEB/Views/Stock/AddDefectJmtDetail.cshtml
@model MES.WEB.Models.DefectDetailVm

<link href="~/Content/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" />

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Добавить в брак</h4>
    </div>

    @using (Html.BeginForm())
    {
        <div class="modal-body">

            @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DetailId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DetailId, ViewBag.Detail as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DetailId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

        <div class="box-footer">
            <button type="submit" class="btn btn-warning pull-right">Добавить</button>
        </div>
    }
</div>



@section scripts {


    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datepicker")



    <script>
        $(function () {
            $(document.body).on('click',
                '[data-val-required]',
                function (ev) {
                    $(ev.target).attr('required', 'true');
                });

            //Date picker
            $('#Date').datepicker({
                language: "ru",
                orientation: "bottom auto",
                todayHighlight: true,
                todayBtn: "linked"

            });
        })
    </script>


   



}

MES.WEB/Views/Stock/Defect.cshtml
@model MES.WEB.Models.DateVm


@{
    ViewBag.Title = "Defect";
}

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div id="alert-message"></div>
<p>
    <a href="@Url.Action("AddDefectJmtDetailPartial")" id="addId" class="btn btn-danger addtn">Добавить в брак</a>
</p>



<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">История прихода деталей на склад</h3>
    </div>
    <!-- /.box-header -->
    <br />
    <div class="form-inline">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <hr />
    <div class="box-body">
        <div id="results">
        </div>
    </div>
</div>




@section scripts
{

    <script>
        function view() {
            var startDate = $('#StartDate').val();
            startDate = encodeURIComponent(startDate);
            var endDate = $('#EndDate').val();
            endDate = encodeURIComponent(endDate);
            $('#results').load('@Url.Action("HistDefectPartial", "Stock")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);

        }

    
        $(function () {
            var idToUpdate = $('#results');
            $.get("/Stock/HistDefectPartial",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });

        $("#stock").className = "active treeview menu-open";
        $("#defectJmtDetail").className = "active";
    </script>


}

MES.WEB/Views/Stock/EditDefect.cshtml
@model MES.WEB.Models.DefectDetailVm

<link href="~/Content/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" />

<div class="modal-content modal-danger">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Редактирование</h4>
    </div>

    @using (Html.BeginForm())
    {
        <div class="modal-body">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>DefectDetailVm</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.DetailId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DetailId, ViewBag.Detail as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DetailId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </div>
    }

</div>

@section scripts {


    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datepicker")



    <script>
        $(function () {
            $(document.body).on('click',
                '[data-val-required]',
                function (ev) {
                    $(ev.target).attr('required', 'true');
                });

            //Date picker
            $('#Date').datepicker({
                language: "ru",
                orientation: "bottom auto",
                todayHighlight: true,
                todayBtn: "linked"

            });
        })
    </script>

MES.WEB/Views/Stock/EditDefectPartial.cshtml
@model MES.WEB.Models.DefectDetailVm

<div id="modalContent" class="modal-content modal-warning">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Добавить в брак</h4>
    </div>

    @using (Ajax.BeginForm("EditDefectPartial",  new AjaxOptions
    {
        UpdateTargetId = "modalContent",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "unloadModal"
    }))
    {
        <div class="modal-body">

            @Html.AntiForgeryToken()

            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DetailId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.DetailId, ViewBag.Detail as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.DetailId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Count, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Count, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Count, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Отмена</button>
            <button type="submit" value="Create" class="btn btn-outline">Добавить</button>
        </div>
    }
</div>



@section scripts {


    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap-datepicker")



    <script>
        $(function () {
            $(document.body).on('click',
                '[data-val-required]',
                function (ev) {
                    $(ev.target).attr('required', 'true');
                });

            //Date picker
            $('#Date').datepicker({
                language: "ru",
                orientation: "bottom auto",
                todayHighlight: true,
                todayBtn: "linked"

            });
        })
    </script>






}

MES.WEB/Views/Stock/EditJmtDetail.cshtml
@model MES.WEB.Models.DetailVm


<div class="modal-content modal-danger">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Редактирование</h4>
    </div>



    @using (Html.BeginForm())
    {
        <div class="modal-body">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.VendorCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.VendorCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VendorCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quantityq, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Quantityq, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Quantityq, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.GroupProductId)


            </div>
            
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Отмена</button>
            <button type="submit" value="Save" class="btn btn-outline">Сохранить изменения</button>
        </div>
            }
   

    </div>

MES.WEB/Views/Stock/EditJmtDetailPartial.cshtml
@model MES.WEB.Models.DetailVm


<div class="modal-content modal-danger">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Редактирование</h4>
    </div>



    @using (Html.BeginForm())
    {
        <div class="modal-body">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.VendorCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.VendorCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VendorCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quantityq, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Quantityq, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Quantityq, "", new { @class = "text-danger" })
                    </div>
                </div>

                @Html.HiddenFor(model => model.GroupProductId)


            </div>
            
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Отмена</button>
            <button type="submit" value="Save" class="btn btn-outline">Сохранить изменения</button>
        </div>
            }
   

    </div>

MES.WEB/Views/Stock/Index.cshtml
@{
    ViewBag.Title = "Склад";
}

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>
<div id="alert-message"></div>

@if (User.IsInRole("admin"))
{
    <p>
        <a href="@Url.Action("AddDetail")" class="btn btn-success addtn">Добавить новую деталь</a>
    </p>
}


<div id="results"></div>


@section scripts
{

    <script>
        function view() {
            var startDate = $('#StartDate').val();
            startDate = encodeURIComponent(startDate);
            var endDate = $('#EndDate').val();
            endDate = encodeURIComponent(endDate);
            $('#results').load('@Url.Action("StockBalanceJmt", "Stock")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);

        }


        $(function () {
            var idToUpdate = $('#results');
            $.get("/Stock/StockBalanceJmt",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });

        document.getElementById("stock").className = "active treeview menu-open";
        document.getElementById("stockBalanceJmt").className = "active";
    </script>


}

MES.WEB/Views/Stock/StockBalanceOw.cshtml
@model IEnumerable<MES.WEB.Models.DetailVm>

@{
    ViewBag.Title = "StockBalanceOw";
}

<div class="box external-event">
    <div class="box-header with-border">
        <h3 class="box-title">5200-01</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <div class="box-body">
        <div class="chart">
            <div id="container" style="width: 100%;">
                <canvas id="Chart520001"></canvas>
            </div>

        </div>
    </div>
</div>


<div class="box">
    <div class="box-header">
        <h3 class="box-title">ЖМТ</h3>
    </div>
    <div class="box-body">
        <table class="table table-bordered table-striped">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VendorCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VendorCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ })

                    </td>
                </tr>
            }

        </table>
    </div>
</div>


<script src="~/Scripts/Chart.min.js"></script>



<script>
    var ctx = document.getElementById("Chart520001").getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: @Html.Raw(Json.Encode(ViewBag.d52001)),
            datasets: [{
                label: '5200-01',
                data: @Html.Raw(Json.Encode(ViewBag.d52001Count)),
                backgroundColor:
                    'rgba(255, 159, 64, 1)'
                ,
                borderColor:
                    'rgba(255, 159, 64, 1)'
                ,
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero:true
                    }
                }]
            }
        }
    });
</script>

MES.WEB/Views/Stock/_AddDetail.cshtml
@model MES.WEB.Models.DetailVm

<div id="modalContent" class="modal-content modal-success">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Добавить новую деталь</h4>
    </div>

    @using (Ajax.BeginForm("AddDetail", new AjaxOptions
    {
        UpdateTargetId = "modalContent",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "unloadModal"
    }))
    {<div class="modal-body">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
               
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.VendorCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.VendorCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VendorCode, "", new { @class = "text-danger" })
                    </div>
                </div>


         </div>
     </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Отмена</button>
            <button type="submit" value="Create" class="btn btn-outline">Сохранить изменения</button>
        </div>
    }

</div>