MES.WEB/Controllers/RepairController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using MES.BLL.DTO;
using MES.BLL.Infrastructure;
using MES.BLL.Interfaces;
using MES.DAL.Entities;
using MES.DAL.Interfaces;
using MES.WEB.Models;

namespace MES.WEB.Controllers
{
    [Authorize]
    public class RepairController : Controller
    {
        private readonly IUnitOfWork _db;

        private readonly IRepairService _service;

        public RepairController(IRepairService service, IUnitOfWork db)
        {
            _service = service;
            _db = db;
        }

        // GET: Repair
        public ActionResult Index()
        {
            var now = DateTime.Now;
            var date = new DateVm
            {
                StartDate = new DateTime(now.Year, now.Month, 1),
                EndDate = now
            };
            return View(date);
        }

        public async Task<ActionResult> AddRepairPartial()
        {
            var repairVm = new RepairVm() { Date = DateTime.Now };
            var products = Mapper.Map<IEnumerable<Product>, List<ProductVm>>(await _db.Products.GetAllAsync());
            ViewBag.Products = new SelectList(products, "Id", "Name");
            return PartialView(repairVm);
        }

        [HttpPost]
        public async Task<ActionResult> AddRepairPartial(RepairVm repairVm)
        {
            repairVm.UserId = User.Identity.GetUserId<int>();
            var products = Mapper.Map<IEnumerable<Product>, List<ProductVm>>(await _db.Products.GetAllAsync());
            ViewBag.Products = new SelectList(products, "Id", "Name");

            if (!ModelState.IsValid)
            {
                return PartialView(repairVm);
            }

            var result = await _service.AddRepairAsync(Mapper.Map<RepairDto>(repairVm));
            return Json(result);
        }

        public async Task<ActionResult> ListPartial(string startDate, string endDate)
        {
            var repairs = Mapper.Map<IEnumerable<RepairDto>, List<RepairVm>>(await _service.ListRepairAsync(startDate, endDate));
            return PartialView(repairs);
        }

        public async Task<ActionResult> Delete(int id)
        {
            var result = await _service.DeleteRepair(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

MES.WEB/Views/Repair/AddRepairPartial.cshtml
@model MES.WEB.Models.RepairVm

<div id="modalContent" class="modal-content modal-success">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title">Добавить ремонт</h4>
    </div>

    @using (Ajax.BeginForm("AddRepairPartial", new AjaxOptions
    {
        UpdateTargetId = "modalContent",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "unloadModal"
    }))
    {
        <div class="modal-body">
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ProductId, ViewBag.Products as SelectList, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RepairsVariant, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.RepairsVariant, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RepairsVariant, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Отмена</button>
            <button type="submit" value="Create" class="btn btn-outline">Сохранить изменения</button>
        </div>
    }

</div>

<script>
    //Date picker
    $('#Date').datepicker({
        language: "ru",
        orientation: "bottom auto",
        todayHighlight: true,
        todayBtn: "linked"
    });

    @*function unloadModal(data) {
        if (data.success) {
            $('#addId').modal('hide');
            window.location.href = "@Url.Action("Index", "Home")";
        }
    };*@
</script>

MES.WEB/Views/Repair/Index.cshtml
@model MES.WEB.Models.DateVm

@{
    ViewBag.Title = "Ремонт";
}

<div id="modDialog" class="modal fade">
    <div id="dialogContent" class="modal-dialog"></div>
</div>


<div id="alert-message"></div>
<p>
    <a href="@Url.Action("AddRepairPartial")" id="addId" class="btn btn-success addtn">Добавить ремонт</a>
</p>
<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">История прихода деталей на склад</h3>
    </div>
    <!-- /.box-header -->
    <br />
    <div class="form-inline">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <hr />
    <div class="box-body">
        <div id="results">
            
        </div>
    </div>
</div>




@section scripts
{





    <script>

        function view() {
            var startDate = $('#StartDate').val();
            startDate = encodeURIComponent(startDate);
            var endDate = $('#EndDate').val();
            endDate = encodeURIComponent(endDate);
            $('#results').load('@Url.Action("ListPartial", "Repair")?startDate=' +
                startDate +
                '&endDate=' +
                endDate);

        }


        $(function () {
            var idToUpdate = $('#results');
            $.get("/Repair/ListPartial",
                function (data) {
                    $(idToUpdate).html(data);
                });
        });


        document.getElementById("repair").className = "active";
    </script>



}

MES.WEB/Views/Repair/ListPartial.cshtml
@model IEnumerable<MES.WEB.Models.RepairVm>


<table id="example" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RepairsVariant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            @if (User.IsInRole("admin"))
            {
                <th></th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td >
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RepairsVariant)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                @if (User.IsInRole("admin"))
                {
                    <td>
                        <a class="text-danger" onclick="deleteElement(event, this)" href="@Url.Action("Delete", new { id = item.Id })">Удалить</a>
                    </td>
                }

            </tr>
        }
    </tbody>
</table>



<script type="text/javascript" charset="utf-8">
    $("#example").dataTable(
        {

            language: {
                "processing": "Подождите...",
                "search": "Поиск:",
                "lengthMenu": "Показать _MENU_ записей",
                "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
                "infoEmpty": "Записи с 0 до 0 из 0 записей",
                "infoFiltered": "(отфильтровано из _MAX_ записей)",
                "infoPostFix": "",
                "loadingRecords": "Загрузка записей...",
                "zeroRecords": "Записи отсутствуют.",
                "emptyTable": "В таблице отсутствуют данные",
                "paginate": {
                    "first": "Первая",
                    "previous": "Предыдущая",
                    "next": "Следующая",
                    "last": "Последняя"
                },
                "aria": {
                    "sortAscending": ": активировать для сортировки столбца по возрастанию",
                    "sortDescending": ": активировать для сортировки столбца по убыванию"
                }
            },

            "aoColumns": [

                { "sType": "ruDate" },
                null,
                null,
                null,
                null
            ],
            "aaSorting": [[0, 'desc']]
        });

    jQuery.extend(jQuery.fn.dataTableExt.oSort,
        {
            "ruDate-asc": function (a, b) {
                var ruDatea = $.trim(a).split('.');
                var ruDateb = $.trim(b).split('.');

                if (ruDatea[2] * 1 < ruDateb[2] * 1)
                    return 1;
                if (ruDatea[2] * 1 > ruDateb[2] * 1)
                    return -1;
                if (ruDatea[2] * 1 == ruDateb[2] * 1) {
                    if (ruDatea[1] * 1 < ruDateb[1] * 1)
                        return 1;
                    if (ruDatea[1] * 1 > ruDateb[1] * 1)
                        return -1;
                    if (ruDatea[1] * 1 == ruDateb[1] * 1) {
                        if (ruDatea[0] * 1 < ruDateb[0] * 1)
                            return 1;
                        if (ruDatea[0] * 1 > ruDateb[0] * 1)
                            return -1;
                    } else
                        return 0;
                }
            },

            "ruDate-desc": function (a, b) {
                var ruDatea = $.trim(a).split('.');
                var ruDateb = $.trim(b).split('.');

                if (ruDatea[2] * 1 < ruDateb[2] * 1)
                    return -1;
                if (ruDatea[2] * 1 > ruDateb[2] * 1)
                    return 1;
                if (ruDatea[2] * 1 == ruDateb[2] * 1) {
                    if (ruDatea[1] * 1 < ruDateb[1] * 1)
                        return -1;
                    if (ruDatea[1] * 1 > ruDateb[1] * 1)
                        return 1;
                    if (ruDatea[1] * 1 == ruDateb[1] * 1) {
                        if (ruDatea[0] * 1 < ruDateb[0] * 1)
                            return -1;
                        if (ruDatea[0] * 1 > ruDateb[0] * 1)
                            return 1;
                    } else
                        return 0;
                }
            }
        });


</script>